apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myweb
  name: myweb
  namespace: jenkins
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myweb
  template:
    metadata:
      labels:
        app: myweb
    spec:
      containers:
        - image: registry.cosmin-lab.cloud:5000/myweb:${commitId}  # Utilizarea variabilei commitId în loc de versiunea statică
          imagePullPolicy: Always
          name: myweb
      imagePullSecrets:
        - name: regcred2

---

apiVersion: v1
kind: Service
metadata:
  name: myweb-service  # Am schimbat numele serviciului
  namespace: jenkins
spec:
  selector:
    app: myweb  # Am actualizat selectorul pentru a se potrivi cu eticheta app din Deployment
  ports:
    - protocol: TCP
      port: 80  # Am schimbat portul la care să fie expus serviciu
      nodePort: 30200  # Poate fi ales din intervalul 30000-32767
  type: NodePort
